PostTaskPropagation.md
I *think* that's `signal`, but please double-check.
There's also a drive-by missing close parenthesis here.
=> Name the field that gets scheduler.currentTaskSignal

PrioritizedPostTask.md
@kenchris: adding text per our [discussion](https://github.com/w3ctag/design-reviews/issues/338#issuecomment-594320007) on the TAG review thread. Is this example/text reasonably clear?
@natechapin can you PTAL?
=> Add new sections for priority overriding signal and onpriortychange

OriginTrialStatus.md
The postTask Origin Trial was recently extended for 2 milestones (through M89), so I'm updating the OT info page.
=> Update Origin Trial information to reflect extension

PrioritizedPostTask.md
The prioritychange event was previously described as the
onprioritychange event, which is incorrect. The event is prioritychange,
and event listeners can be added either with
signal.addEventListener('prioritychange') or the signal.onprioritychange
property.
=> Fix language around prioritychange event

explainers/prioritized-post-task.md
In addition to some minor edits, the main changes are:
* Add an explicit goals and non-goals section
* Add metadata (author, issue tracker, spec)
* Clean up introduction prose
* Reorder and tweak post-MVP exploration
* Mention API shape evolution
=> postTask explainer cleanup

spec/scheduling-tasks.md
This closes #42 (thanks @annevk!).
@domenic is it acceptable to word it like this, or should this be a separate step?
=> [spec] Change 'schedule a postTask task' to actually return the promise

explainers/post-task-propagation.md, explainers/prioritized-post-task.md, sample-code/controlling-scheduled-tasks.html, sample-code/tasksignal-propagation.html, spec/controlling-tasks.md
Closes #26.
Previously, the TaskController constructor had a single optional priority parameter. While there is a low likelihood that we'll add a parameter to this or AbortController, changing this to a dictionary helps future-proof the API in the case that we do (per https://w3ctag.github.io/design-principles/#prefer-dict-to-bool).
=> Change TaskController constructor to take an optional dictionary

spec/scheduling-tasks.md
Part of https://github.com/whatwg/dom/issues/1030. Basically, now `AbortSignal`s can be aborted with custom abort reasons, e.g. `"TimeoutError"` `DOMException`s being a prominent case, so downstream specs need to support this.
*This is a normative change* so please remember to implement it :).
=> Update for AbortSignal's abort reason

spec/scheduling-tasks.md
This is on top of #53 since that's necessary to get the build working.
Don't merge until https://github.com/whatwg/html/pull/7349 is merged, but review is appreciated. (Probably best to view a single commit at a time.)
=> Use HTML's "wait for timeout"

spec/patches.md
This makes the spec consistent Chromium's implementation, which was
was the intended behavior to avoid potential name conflicts with the
generic term.
Closes #58.
=> Mark the scheduler attribute as [Replaceable]

explainers/archived/old-yield-and-continuation.md
Making room for a revised, more complete explainer.
=> Archive previous scheduler.yield() explainer

spec/index.bs
Fixes #66.
***
<a href="https://pr-preview.s3.amazonaws.com/shaseley/scheduling-apis/pull/68.html" title="Last updated on Mar 14, 2023, 10:27 PM UTC (a3f5f7f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/scheduling-apis/68/08ddfbb...shaseley:a3f5f7f.html" title="Last updated on Mar 14, 2023, 10:27 PM UTC (a3f5f7f)">Diff</a>
=> Fix broken HTML links

spec/scheduling-tasks.md, spec/security.md
Editorial fix: remove line breaks in definitions and references. The new bikeshed HTML parser does not insert spaces, which broke linking.
=> Fix line breaks

spec/controlling-tasks.md, spec/index.bs, spec/scheduling-tasks.md
Specialization of [`AbortSignal.any()`](https://github.com/whatwg/dom/pull/1152) for TaskSignal.any(). It supports creating a composite signal with multiple abort sources and either a fixed priority or single priority source. The spec is similar to `AbortSignal.any()` and uses the internal constructor for the abort aspect.
Tests: https://github.com/web-platform-tests/wpt/tree/master/scheduler (task-signal-any*).
***
<a href="https://pr-preview.s3.amazonaws.com/shaseley/scheduling-apis/pull/72.html" title="Last updated on May 17, 2023, 5:36 PM UTC (e816db8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/scheduling-apis/72/38dd556...shaseley:e816db8.html" title="Last updated on May 17, 2023, 5:36 PM UTC (e816db8)">Diff</a>
=> Add TaskSignal.any()

explainers/yield-and-continuation.md
There's nothing in the spec called a "macrotask", it's simply "task". Not only does "macrotask" not exist, it looks visually similar to "microtask", which is a thing, but a different thing.
=> "macrotask" isn't a thing

spec/controlling-tasks.md, spec/index.bs, spec/introduction.md, spec/patches.md, spec/privacy.md, spec/scheduling-tasks.md, spec/security.md
- Use column width 100 (previously 80)
- Reorganize sections to not mix algorithms and data
- Factor out TaskSignal.any() algorithm
- Remove unnecessary "perform the following steps:" at the end of algorithm definitions
- Remove link tag conjugations that bikeshed can handle
- Use consistent heading syntax
***
<a href="https://pr-preview.s3.amazonaws.com/shaseley/scheduling-apis/pull/75.html" title="Last updated on Apr 4, 2024, 4:45 PM UTC (daa4bb0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/scheduling-apis/75/344e410...shaseley:daa4bb0.html" title="Last updated on Apr 4, 2024, 4:45 PM UTC (daa4bb0)">Diff</a>
=> Editorial: Clean up spec markdown

spec/controlling-tasks.md, spec/index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/shaseley/scheduling-apis/pull/85.html" title="Last updated on Apr 5, 2024, 11:53 PM UTC (8f6fafe)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/scheduling-apis/85/27cd411...shaseley:8f6fafe.html" title="Last updated on Apr 5, 2024, 11:53 PM UTC (8f6fafe)">Diff</a>
=> Editorial: Parameterize TaskSignal.any() realm and fix linking

spec/scheduling-tasks.md
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/scheduling-apis/pull/90.html" title="Last updated on Apr 25, 2024, 5:39 PM UTC (88ee673)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/scheduling-apis/90/d1bf8ab...88ee673.html" title="Last updated on Apr 25, 2024, 5:39 PM UTC (88ee673)">Diff</a>
=> Trivial readability changes to scheduling-tasks doc

spec/scheduling-tasks.md
This introduces removal of abort algorithms and task queue map entries on abort and task completion:
- Add a helper struct (task handle) to store state and algorithms needed to clean up on abort/task complete. It was a bit cleaner to keep this all together.
- On abort and task complete, remove the task queue map entry if the queue became empty
- On task complete, remove the abort algorithm
- On abort, remove the pending task
Notes:
1. This also fixes a spec bug where it was possible for delayed tasks not to be aborted if the abort happened while waiting to queue the task. This is fixed here by moving up the point where we add the abort algorithm and conditionally and adjusting the algorithm to handle the case where the task hasn't been queued yet (during delay).
2. For delayed tasks, …
=> Clean up abort algorithms and task queue map entries

spec/patches.md, spec/scheduling-tasks.md
The postTask spec allows the next Scheduler task to be the oldest, highest priority task from any of its task queues, enabling per-frame task prioritization decisions. But HTML task queues are per agent/event loop, and as such other scheduling decisions typically cannot take into account a task's frame. It's not clear there's a benefit to enabling some tasks to be per frame while others are per agent, and removing this simplifies things and makes overall prioritization easier to understand, which is what this change does.
***
<a href="https://pr-preview.s3.amazonaws.com/shaseley/scheduling-apis/pull/87.html" title="Last updated on Apr 29, 2024, 9:33 PM UTC (830630f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/scheduling-apis/87/239d8c2...shaseley:830630f.html" …
=> Make task queue selection per agent rather than per scheduler

explainers/prioritized-task-scheduling.md
Add an explainer tying together the various Scheduling API proposals, which TAG [mentioned](https://github.com/w3ctag/design-reviews/issues/827) requested, and which I agree would be helpful.
=> Add a meta explainer

spec/controlling-tasks.md, spec/introduction.md, spec/patches.md, spec/scheduling-tasks.md
Implementation notes:
- Refactor existing spec to share as much as possible between `yield()` and `postTask()`:
- Extract out "scheduling state" struct to hold abort and priority sources and compute this based the options passed to `postTask()` and `yield()`
- Change map data structures and related algorithms to additionally be keyed on "is continuation" boolean (the queues need to be separate since the effective priorities are different)
- Unify `postTask()` and `yield()` priority with notion of an "effective priority", which is used for picking the next task to run (`yield()` effective priority for a given task priority is just higher than `postTask()` equivalent).
- Implement inheritance by adding notion of "current scheduling state" to the event loop
- Set before running `postTask()` …
=> Add specification for scheduler.yield() method

spec/security.md
This updates the security section to include `yield()`, which has the same priority-based security implications as `postTask()`.
***
<a href="https://pr-preview.s3.amazonaws.com/shaseley/scheduling-apis/pull/91.html" title="Last updated on May 29, 2024, 11:37 PM UTC (33e01ca)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/scheduling-apis/91/e6c47f5...shaseley:33e01ca.html" title="Last updated on May 29, 2024, 11:37 PM UTC (33e01ca)">Diff</a>
=> yield: Update security section

spec/patches.md, spec/scheduling-tasks.md
- Reword priority spec section to more closely match the recently added meta explainer
- Add a note in the HTML event loop processing section to describe the intent of the Scheduler priorities wrt event loop integration, along with an example strategy (which ~= what we do in Chromium)
***
<a href="https://pr-preview.s3.amazonaws.com/shaseley/scheduling-apis/pull/92.html" title="Last updated on Jun 5, 2024, 6:00 PM UTC (7395c3a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/scheduling-apis/92/0a23970...shaseley:7395c3a.html" title="Last updated on Jun 5, 2024, 6:00 PM UTC (7395c3a)">Diff</a>
=> Clarify event loop integration and prioritization

spec/scheduling-tasks.md
Fixes #97.
***
<a href="https://pr-preview.s3.amazonaws.com/shaseley/scheduling-apis/pull/99.html" title="Last updated on Jul 10, 2024, 5:53 PM UTC (0fe2e6a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/scheduling-apis/99/054fcc5...shaseley:0fe2e6a.html" title="Last updated on Jul 10, 2024, 5:53 PM UTC (0fe2e6a)">Diff</a>
=> Fix xref in 'schedule a yield continuation'

spec/scheduling-tasks.md
By default, scheduler.yield() continuations inherit the priority and abort signal from the current task, but this behavior can be overridden by providing a signal or priority option. But it's not clear if this is necessary, and there are questions around the expectations of subsequent continuations (see https://github.com/WICG/scheduling-apis/issues/96).
To simplify the API, for now we're removing the yield() parameters, instead always using the inherited state. We can revisit this as use cases arise.
***
<a href="https://pr-preview.s3.amazonaws.com/shaseley/scheduling-apis/pull/100.html" title="Last updated on Aug 1, 2024, 8:33 PM UTC (f21749b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/scheduling-apis/100/041dc73...shaseley:f21749b.html" title="Last updated on Aug …
=> Remove scheduler.yield() parameters

spec/security.md
I'm not sure how this made it through in the change that removed ContinuationPriority, but this removes a stale reference to ContinuationPriority.
***
<a href="https://pr-preview.s3.amazonaws.com/shaseley/scheduling-apis/pull/103.html" title="Last updated on Aug 9, 2024, 9:55 PM UTC (baa04a6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/scheduling-apis/103/ab9bdc9...shaseley:baa04a6.html" title="Last updated on Aug 9, 2024, 9:55 PM UTC (baa04a6)">Diff</a>
=> Editorial: Fix bad linking due to removed ContinuationPriority

spec/scheduling-tasks.md
Part of whatwg/webidl#1425.
***
<a href="https://pr-preview.s3.amazonaws.com/jeremyroman/scheduling-apis/pull/102.html" title="Last updated on Aug 12, 2024, 2:51 PM UTC (97cbe1e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/scheduling-apis/102/4b53840...jeremyroman:97cbe1e.html" title="Last updated on Aug 12, 2024, 2:51 PM UTC (97cbe1e)">Diff</a>
=> Editorial: Update use of WebIDL "invoke a callback function"

spec/scheduling-tasks.md
following removal in #100, presumably these need to go too
(Incidentally, bikeshed errors for me, but I eventually found https://github.com/speced/bikeshed/issues/2621 which fixes the link error for me too. Somehow the github action is working, though? 🤷)
***
<a href="https://pr-preview.s3.amazonaws.com/brendankenny/scheduling-apis/pull/105.html" title="Last updated on Aug 22, 2024, 7:53 PM UTC (426c398)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/scheduling-apis/105/714aeb3...brendankenny:426c398.html" title="Last updated on Aug 22, 2024, 7:53 PM UTC (426c398)">Diff</a>
=> Editorial: Remove remaining references to scheduler.yield options

spec/scheduling-tasks.md
"schedule a yield continuation" was not taking into account that the current scheduling state can be null, in which case the priority source and abort source are null, and a non-abortable, user-visible continuation should be scheduled. The latter is handled already by the abort and priority source null checks, but these weren't being initialized to null if the inherited scheduling state is null.
Fixes #106
***
<a href="https://pr-preview.s3.amazonaws.com/shaseley/scheduling-apis/pull/107.html" title="Last updated on Sep 16, 2024, 5:15 PM UTC (bda2446)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/scheduling-apis/107/00a8773...shaseley:bda2446.html" title="Last updated on Sep 16, 2024, 5:15 PM UTC (bda2446)">Diff</a>
=> yield: Add null check for inherited state in spec

spec/scheduling-tasks.md
It seems to me that there is a mistake here and the word is repeated twice.
***
<a href="https://pr-preview.s3.amazonaws.com/WOLFRIEND/scheduling-apis/pull/116.html" title="Last updated on Apr 1, 2025, 11:33 AM UTC (e579bf0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/scheduling-apis/116/83873f3...WOLFRIEND:e579bf0.html" title="Last updated on Apr 1, 2025, 11:33 AM UTC (e579bf0)">Diff</a>
=> Fix typo in "scheduling-tasks.md".
